# Site settings
title: Matheus Bras | Ruby Developer
description: > # this means to ignore newlines until "baseurl:"
  Matheus Bras | Ruby Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matheusbras.com.br" # the base hostname & protocol for your site
twitter_username: matheusbras_
github_username:  matheusbras

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass